{% set name = "alibabacloud-tea-xml" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_xml-{{ version }}.tar.gz
  sha256: f0135e8148fd7d9c1f029db161863f37f144f837c280cba16c2edeb2f9c549d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - alibabacloud-tea >=0.0.1

test:
  imports:
    - alibabacloud_tea_xml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/tea-xml/tree/master/python
  summary: The tea-xml module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
