{% set name = "alibabacloud-tea-xml" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_xml-{{ version }}.tar.gz
  sha256: 979cb51fadf43de77f41c69fc69c12529728919f849723eb0cd24eb7b048a90c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea >=0.4.0

test:
  imports:
    - alibabacloud_tea_xml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/tea-xml/tree/master/python
  summary: The tea-xml module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
